{% set name = "lark-parser" %}
{% set version = "0.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lark-parser-{{ version }}.tar.gz
  sha256: e29ca814a98bb0f81674617d878e5f611cb993c19ea47f22c80da3569425f9bd

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - lark
    - lark.parsers
    - lark.tools

about:
  home: https://github.com/erezsh/lark
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a modern parsing library

  description: |
    Lark is a modern general-purpose parsing library for Python.
    With Lark, you can parse any context-free grammar, efficiently, with very little code.
    Main Features:
     - Builds a parse-tree (AST) automagically, based on the structure of the grammar
     - Earley parser
        - Can parse all context-free grammars
        - Full support for ambiguous grammars
     - LALR(1) parser
        - Fast and light, competitive with PLY
        - Can generate a stand-alone parser
     - CYK parser, for highly ambiguous grammars
     - EBNF grammar
     - Unicode fully supported
     - Python 2 & 3 compatible
     - Automatic line & column tracking
     - Standard library of terminals (strings, numbers, names, etc.)
     - Import grammars from Nearley.js
     - Extensive test suite
     - And much more!
  doc_url: http://lark-parser.readthedocs.io/
  dev_url: https://github.com/erezsh/lark

extra:
  recipe-maintainers:
    - tarcisioe
    - mlin
