travis:
  secure:
    BINSTAR_TOKEN: k9OpmPwm7kVNPvltLx4dQnsVdw706AYrJ/IVTzXtqSZcyiRtZG0/r6xx/kzE2GJh0QY18uuA/ZWQk18Czc3ri5lSerf5CuR/PdWMwoAzNF1KC77se8Vs9a5iWVRu7m360w3lb/dWDr07MGfyqGNVt4bGal/TENtKwqqDomyf0WvT5qb1FfqCxmZ4BwipllRnJTwXcAArjstao7qKsO67EUxyB8EmbLCbSUl3JE+oxo+ZFsTxca9ReKqMJkj10EzWUUlBg6TN2XthjzxyXwKJvj6SBSb4Vwu/W3jR5uJRK1X6AEanzmIcRQKmo7DlLmudMlMNPI/+E/NGAPzghRW/oZTU2h9BwQ/k+f0qfOG4c/EG35ptuuHQRs5HLVkEah6HoaMDb/ek4iOMIATgHmrpY38Hugd3ZIWWgxwNdgTkrsFHdGqc3iBPIJrO+6M3bRFSVolaR+GQQPeLW+dsJ1UHwgRPGOTcadWPU8oWWuy9LRgN+gbxYnoY89uQIQqXvuJCvbQLdHhwMPNweJCnGt6G86zInpXq4hoaRWO8yN0VJ+8iOs7tVyju27BfMPmtmUmHSqzBVy2Gj1SyTFcQXlO9Mg7BMCWBettRkHSwK15JDjOn0KqE3jLn11wjve4H82Fbz6IhPyyQxOPlKfBl4WW+SYDN0grj6P3WVlgPEJrfqwY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
